## Plan of Action
1. <i>We will build a simple neural network
2. Train it on a real world dataset
3. Will mimic the PyTorch workflow</i>

### Codeflow
1. <i>Load the dataset
2. Basic preprocessing
3. Training Process
  - 1. Create the model
  - 2. Forward pass
  - 3. Loss calculation
  - 4. Backprop
  - 5. Parameters update
4. Model evaluation</i>

In [122]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [123]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [124]:
df.shape

(569, 33)

In [125]:
df.drop(columns=["id", "Unnamed: 32"], inplace = True)

In [126]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### Train Test Split

In [127]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [128]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [129]:
X_train

array([[ 0.28455879, -0.62194576,  0.28423625, ...,  0.16182573,
         0.84523165,  0.75634496],
       [-0.50786648, -0.18988937, -0.5398084 , ..., -0.46352017,
         0.14633283, -0.6615762 ],
       [-0.68300395, -0.41753198, -0.6698549 , ..., -0.20927213,
        -0.67066695, -0.34413944],
       ...,
       [ 1.2865748 ,  0.20732376,  1.25625047, ...,  0.52678974,
        -0.89230847, -0.53060579],
       [-1.10218543,  1.91696625, -1.09584055, ..., -0.358478  ,
        -1.07835792, -0.05223082],
       [ 0.23574999, -0.13646304,  0.24505557, ..., -0.46919398,
        -0.06560177,  0.46665617]])

In [130]:
y_train

205    M
107    B
530    B
289    B
244    M
      ..
477    B
161    M
27     M
555    B
147    B
Name: diagnosis, Length: 455, dtype: object

In [131]:
# Need to encode labels
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [132]:
y_train

array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0])

### Numpy arrays to Pytorch Tensors

In [133]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [134]:
X_train_tensor

tensor([[ 0.2846, -0.6219,  0.2842,  ...,  0.1618,  0.8452,  0.7563],
        [-0.5079, -0.1899, -0.5398,  ..., -0.4635,  0.1463, -0.6616],
        [-0.6830, -0.4175, -0.6699,  ..., -0.2093, -0.6707, -0.3441],
        ...,
        [ 1.2866,  0.2073,  1.2563,  ...,  0.5268, -0.8923, -0.5306],
        [-1.1022,  1.9170, -1.0958,  ..., -0.3585, -1.0784, -0.0522],
        [ 0.2357, -0.1365,  0.2451,  ..., -0.4692, -0.0656,  0.4667]],
       dtype=torch.float64)

In [135]:
X_train_tensor.shape

torch.Size([455, 30])

In [136]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [137]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True) # 30x1 matrix
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True) # onlu 1 neuron so 1 bias

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias # z = w*x + b
    y_pred = torch.sigmoid(z) # activation function (sigmoid)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameters

In [138]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [139]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
    # since we dont need gradient tracking during parameter update use below line otherwise will throw error
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # disable gradient tracking i.e. reset the gradients or avoid gradient accumulation (zero gradients)
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print the loss in each epoch
  print(f"Epoch: {epoch + 1}, loss: {loss.item()}")

Epoch: 1, loss: 3.75015622168555
Epoch: 2, loss: 3.6188173904349514
Epoch: 3, loss: 3.48322139456403
Epoch: 4, loss: 3.342494209126483
Epoch: 5, loss: 3.2016366941587773
Epoch: 6, loss: 3.0621369344060896
Epoch: 7, loss: 2.9185640913653628
Epoch: 8, loss: 2.7724171266246485
Epoch: 9, loss: 2.6248717758362345
Epoch: 10, loss: 2.4703456681293554
Epoch: 11, loss: 2.3047535354454487
Epoch: 12, loss: 2.1393168156177946
Epoch: 13, loss: 1.9723438956303914
Epoch: 14, loss: 1.8093982192199158
Epoch: 15, loss: 1.654009650580021
Epoch: 16, loss: 1.509052486636524
Epoch: 17, loss: 1.3738585382046171
Epoch: 18, loss: 1.2538109132077215
Epoch: 19, loss: 1.1504097676427247
Epoch: 20, loss: 1.0644789642875954
Epoch: 21, loss: 0.9956207295036876
Epoch: 22, loss: 0.9418195219947293
Epoch: 23, loss: 0.9001833690095468
Epoch: 24, loss: 0.8679548377811885
Epoch: 25, loss: 0.8428329183103929

In [140]:
#print(model.weights)
print(model.bias)

tensor([-0.1422], dtype=torch.float64, requires_grad=True)

### Model Evaluation

In [141]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor) # sigmoid value between 0 and 1
  y_pred = (y_pred > 0.5).float() # value of y_pred > 0.5 is 1
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5236995816230774