- TMDB API : https://developers.themoviedb.org/
https://developer.themoviedb.org/reference/movie-top-rated-list
- RapidAPI : https://rapidapi.com/collection/list-of-free-apis
- JSON Viewer: http://jsonviewer.stack.hu/

In [96]:
import pandas as pd
import requests # create http request

In [97]:
# request the server to fetch details using api key
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=7fbc7861cb903f427b0dfbe8f72a6be3&language=en-US&page=1')

In [98]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 86.3449,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.911,
   'vote_count': 1899},
  {'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 163.2599,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.724,
   'vote_count': 30727},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'genre_ids': [10402, 18],
   'id': 936075,
   'title': 'Michael',
   'original_language': 'en',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'popularity': 170.165,
   'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.703,
   'vote_count': 3383},
  {'adult': False,
   'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 39.4047,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.687,
   'vote_count': 23134},
  {'adult': False,
   'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 167.206,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.675,
   'vote_count': 5868},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 27.3813,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.571,
   'vote_count': 14026},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 23.0698,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.57,
   'vote_count': 17581},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 24.6296,
   'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.565,
   'vote_count': 10100},
  {'adult': False,
   'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
   'genre_ids': [18, 9648],
   'id': 1330021,
   'title': 'Remarkably Bright Creatures',
   'original_language': 'en',
   'original_title': 'Remarkably Bright Creatures',
   'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
   'popularity': 21.6499,
   'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
   'release_date': '2026-05-07',
   'softcore': False,
   'video': False,
   'vote_average': 8.553,
   'vote_count': 705},
  {'adult': False,
   'backdrop_path': '/vpuPY4UziUCxv7gYYoaZQ3LX7to.jpg',
   'genre_ids': [28, 53],
   'id': 1383731,
   'title': 'Protector',
   'original_language': 'en',
   'original_title': 'Protector',
   'overview': "Nikki's life is shattered when her daughter is kidnapped. Thrust into the criminal underworld while hunted by cops and military, she must fight to rescue her child.",
   'popularity': 18.7465,
   'poster_path': '/icOZpnGuH9YrEaW3wrw5GJaXGih.jpg',
   'release_date': '2026-02-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.545,
   'vote_count': 413},
  {'adult': False,
   'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 36.445,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.535,
   'vote_count': 18506},
  {'adult': False,
   'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 39.843,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.532,
   'vote_count': 36052},
  {'adult': False,
   'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'title': 'Dilwale Dulhania Le Jayenge',
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 13.1624,
   'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg',
   'release_date': '1995-10-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.51,
   'vote_count': 4600},
  {'adult': False,
   'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 27.3229,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.507,
   'vote_count': 19408},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 35.691,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 26802},
  {'adult': False,
   'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
   'genre_ids': [35, 10749],
   'id': 1181678,
   'title': '¿Quieres ser mi hijo?',
   'original_language': 'en',
   'original_title': '¿Quieres ser mi hijo?',
   'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
   'popularity': 10.1749,
   'poster_path': '/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg',
   'release_date': '2023-09-21',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 355},
  {'adult': False,
   'backdrop_path': '/wCuUKiRaz0wEESsYqmQy005xvTE.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'title': 'Parasite',
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 29.4182,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'softcore': False,
   'video': False,
   'vote_average': 8.492,
   'vote_count': 20839},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80, 35],
   'id': 680,
   'title': 'Pulp Fiction',
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 35.3552,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.482,
   'vote_count': 30387},
  {'adult': False,
   'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'title': 'Your Name.',
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 26.5695,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-07-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.481,
   'vote_count': 12677},
  {'adult': False,
   'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'title': 'Interstellar',
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 61.1834,
   'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
   'release_date': '2014-11-05',
   'softcore': False,
   'video': False,
   'vote_average': 8.481,
   'vote_count': 40247}],
 'total_pages': 549,
 'total_results': 10979}

In [99]:
# we only want the results part
response.json()['results']

[{'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 86.3449,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.911,
  'vote_count': 1899},
 {'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 163.2599,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.724,
  'vote_count': 30727},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'genre_ids': [10402, 18],
  'id': 936075,
  'title': 'Michael',
  'original_language': 'en',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'popularity': 170.165,
  'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.703,
  'vote_count': 3383},
 {'adult': False,
  'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 39.4047,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.687,
  'vote_count': 23134},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 167.206,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.675,
  'vote_count': 5868},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 27.3813,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.571,
  'vote_count': 14026},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 23.0698,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.57,
  'vote_count': 17581},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 24.6296,
  'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.565,
  'vote_count': 10100},
 {'adult': False,
  'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
  'genre_ids': [18, 9648],
  'id': 1330021,
  'title': 'Remarkably Bright Creatures',
  'original_language': 'en',
  'original_title': 'Remarkably Bright Creatures',
  'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
  'popularity': 21.6499,
  'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
  'release_date': '2026-05-07',
  'softcore': False,
  'video': False,
  'vote_average': 8.553,
  'vote_count': 705},
 {'adult': False,
  'backdrop_path': '/vpuPY4UziUCxv7gYYoaZQ3LX7to.jpg',
  'genre_ids': [28, 53],
  'id': 1383731,
  'title': 'Protector',
  'original_language': 'en',
  'original_title': 'Protector',
  'overview': "Nikki's life is shattered when her daughter is kidnapped. Thrust into the criminal underworld while hunted by cops and military, she must fight to rescue her child.",
  'popularity': 18.7465,
  'poster_path': '/icOZpnGuH9YrEaW3wrw5GJaXGih.jpg',
  'release_date': '2026-02-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.545,
  'vote_count': 413},
 {'adult': False,
  'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 36.445,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.535,
  'vote_count': 18506},
 {'adult': False,
  'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 39.843,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.532,
  'vote_count': 36052},
 {'adult': False,
  'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'title': 'Dilwale Dulhania Le Jayenge',
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 13.1624,
  'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg',
  'release_date': '1995-10-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.51,
  'vote_count': 4600},
 {'adult': False,
  'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 27.3229,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.507,
  'vote_count': 19408},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 35.691,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 26802},
 {'adult': False,
  'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
  'genre_ids': [35, 10749],
  'id': 1181678,
  'title': '¿Quieres ser mi hijo?',
  'original_language': 'en',
  'original_title': '¿Quieres ser mi hijo?',
  'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
  'popularity': 10.1749,
  'poster_path': '/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg',
  'release_date': '2023-09-21',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 355},
 {'adult': False,
  'backdrop_path': '/wCuUKiRaz0wEESsYqmQy005xvTE.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'title': 'Parasite',
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 29.4182,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.492,
  'vote_count': 20839},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80, 35],
  'id': 680,
  'title': 'Pulp Fiction',
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 35.3552,
  'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  'release_date': '1994-09-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.482,
  'vote_count': 30387},
 {'adult': False,
  'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'title': 'Your Name.',
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 26.5695,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-07-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.481,
  'vote_count': 12677},
 {'adult': False,
  'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
  'genre_ids': [12, 18, 878],
  'id': 157336,
  'title': 'Interstellar',
  'original_language': 'en',
  'original_title': 'Interstellar',
  'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  'popularity': 61.1834,
  'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
  'release_date': '2014-11-05',
  'softcore': False,
  'video': False,
  'vote_average': 8.481,
  'vote_count': 40247}]

In [100]:
# convert the list response.json()['results'] to dataframe
pd.DataFrame(response.json()['results']).head(2)

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",86.3449,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.911,1899
1,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,163.2599,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.724,30727

In [101]:
# extract selective columns and assign to temp_df
temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]

In [102]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,86.3449,8.911,1899
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,163.2599,8.724,30727
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,170.1650,8.703,3383
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,39.4047,8.687,23134
4,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,167.2060,8.675,5868

In [103]:
# in response.json() output you can see that there are 549 pages, and we are at page 1 currently
# so we will iterate through all these pages and append them to the older dataframe

df = pd.DataFrame() # creating empty dataframe
df

Empty DataFrame
Columns: []
Index: []

In [104]:
#a = response.json()['total_pages'] # get total pages at page 501 getting error
for i in range (1,500):
  response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=7fbc7861cb903f427b0dfbe8f72a6be3&language=en-US&page={}'.format(i))
  temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]
  print("Results from Page {} extracted.".format(i))
  df = pd.concat([df, temp_df], ignore_index=True) # to avoide the same index in every iteration concatenated (Note: df.append() method doesnt work) append method was completely removed in Pandas 2.0

Results from Page 1 extracted.
Results from Page 2 extracted.
Results from Page 3 extracted.
Results from Page 4 extracted.
Results from Page 5 extracted.
Results from Page 6 extracted.
Results from Page 7 extracted.
Results from Page 8 extracted.
Results from Page 9 extracted.
Results from Page 10 extracted.
Results from Page 11 extracted.
Results from Page 12 extracted.
Results from Page 13 extracted.
Results from Page 14 extracted.
Results from Page 15 extracted.
Results from Page 16 extracted.
Results from Page 17 extracted.
Results from Page 18 extracted.
Results from Page 19 extracted.
Results from Page 20 extracted.
Results from Page 21 extracted.
Results from Page 22 extracted.
Results from Page 23 extracted.
Results from Page 24 extracted.
Results from Page 25 extracted.
Results from Page 26 extracted.
Results from Page 27 extracted.
Results from Page 28 extracted.
Results from Page 29 extracted.
Results from Page 30 extracted.
Results from Page 31 extracted.
Results from Page 32 extracted.
Results from Page 33 extracted.
Results from Page 34 extracted.
Results from Page 35 extracted.
Results from Page 36 extracted.
Results from Page 37 extracted.
Results from Page 38 extracted.
Results from Page 39 extracted.
Results from Page 40 extracted.
Results from Page 41 extracted.
Results from Page 42 extracted.
Results from Page 43 extracted.
Results from Page 44 extracted.
Results from Page 45 extracted.
Results from Page 46 extracted.
Results from Page 47 extracted.
Results from Page 48 extracted.
Results from Page 49 extracted.
Results from Page 50 extracted.
Results from Page 51 extracted.
Results from Page 52 extracted.
Results from Page 53 extracted.
Results from Page 54 extracted.
Results from Page 55 extracted.
Results from Page 56 extracted.
Results from Page 57 extracted.
Results from Page 58 extracted.
Results from Page 59 extracted.
Results from Page 60 extracted.
Results from Page 61 extracted.
Results from Page 62 extracted.
Results from Page 63 extracted.
Results from Page 64 extracted.
Results from Page 65 extracted.
Results from Page 66 extracted.
Results from Page 67 extracted.
Results from Page 68 extracted.
Results from Page 69 extracted.
Results from Page 70 extracted.
Results from Page 71 extracted.
Results from Page 72 extracted.
Results from Page 73 extracted.
Results from Page 74 extracted.
Results from Page 75 extracted.
Results from Page 76 extracted.
Results from Page 77 extracted.
Results from Page 78 extracted.
Results from Page 79 extracted.
Results from Page 80 extracted.
Results from Page 81 extracted.
Results from Page 82 extracted.
Results from Page 83 extracted.
Results from Page 84 extracted.
Results from Page 85 extracted.
Results from Page 86 extracted.
Results from Page 87 extracted.
Results from Page 88 extracted.
Results from Page 89 extracted.
Results from Page 90 extracted.
Results from Page 91 extracted.
Results from Page 92 extracted.
Results from Page 93 extracted.
Results from Page 94 extracted.
Results from Page 95 extracted.
Results from Page 96 extracted.
Results from Page 97 extracted.
Results from Page 98 extracted.
Results from Page 99 extracted.
Results from Page 100 extracted.
Results from Page 101 extracted.
Results from Page 102 extracted.
Results from Page 103 extracted.
Results from Page 104 extracted.
Results from Page 105 extracted.
Results from Page 106 extracted.
Results from Page 107 extracted.
Results from Page 108 extracted.
Results from Page 109 extracted.
Results from Page 110 extracted.
Results from Page 111 extracted.
Results from Page 112 extracted.
Results from Page 113 extracted.
Results from Page 114 extracted.
Results from Page 115 extracted.
Results from Page 116 extracted.
Results from Page 117 extracted.
Results from Page 118 extracted.
Results from Page 119 extracted.
Results from Page 120 extracted.
Results from Page 121 extracted.
Results from Page 122 extracted.
Results from Page 123 extracted.
Results from Page 124 extracted.
Results from Page 125 extracted.
Results from Page 126 extracted.
Results from Page 127 extracted.
Results from Page 128 extracted.
Results from Page 129 extracted.
Results from Page 130 extracted.
Results from Page 131 extracted.
Results from Page 132 extracted.
Results from Page 133 extracted.
Results from Page 134 extracted.
Results from Page 135 extracted.
Results from Page 136 extracted.
Results from Page 137 extracted.
Results from Page 138 extracted.
Results from Page 139 extracted.
Results from Page 140 extracted.
Results from Page 141 extracted.
Results from Page 142 extracted.
Results from Page 143 extracted.
Results from Page 144 extracted.
Results from Page 145 extracted.
Results from Page 146 extracted.
Results from Page 147 extracted.
Results from Page 148 extracted.
Results from Page 149 extracted.
Results from Page 150 extracted.
Results from Page 151 extracted.
Results from Page 152 extracted.
Results from Page 153 extracted.
Results from Page 154 extracted.
Results from Page 155 extracted.
Results from Page 156 extracted.
Results from Page 157 extracted.
Results from Page 158 extracted.
Results from Page 159 extracted.
Results from Page 160 extracted.
Results from Page 161 extracted.
Results from Page 162 extracted.
Results from Page 163 extracted.
Results from Page 164 extracted.
Results from Page 165 extracted.
Results from Page 166 extracted.
Results from Page 167 extracted.
Results from Page 168 extracted.
Results from Page 169 extracted.
Results from Page 170 extracted.
Results from Page 171 extracted.
Results from Page 172 extracted.
Results from Page 173 extracted.
Results from Page 174 extracted.
Results from Page 175 extracted.
Results from Page 176 extracted.
Results from Page 177 extracted.
Results from Page 178 extracted.
Results from Page 179 extracted.
Results from Page 180 extracted.
Results from Page 181 extracted.
Results from Page 182 extracted.
Results from Page 183 extracted.
Results from Page 184 extracted.
Results from Page 185 extracted.
Results from Page 186 extracted.
Results from Page 187 extracted.
Results from Page 188 extracted.
Results from Page 189 extracted.
Results from Page 190 extracted.
Results from Page 191 extracted.
Results from Page 192 extracted.
Results from Page 193 extracted.
Results from Page 194 extracted.
Results from Page 195 extracted.
Results from Page 196 extracted.
Results from Page 197 extracted.
Results from Page 198 extracted.
Results from Page 199 extracted.
Results from Page 200 extracted.
Results from Page 201 extracted.
Results from Page 202 extracted.
Results from Page 203 extracted.
Results from Page 204 extracted.
Results from Page 205 extracted.
Results from Page 206 extracted.
Results from Page 207 extracted.
Results from Page 208 extracted.
Results from Page 209 extracted.
Results from Page 210 extracted.
Results from Page 211 extracted.
Results from Page 212 extracted.
Results from Page 213 extracted.
Results from Page 214 extracted.
Results from Page 215 extracted.
Results from Page 216 extracted.
Results from Page 217 extracted.
Results from Page 218 extracted.
Results from Page 219 extracted.
Results from Page 220 extracted.
Results from Page 221 extracted.
Results from Page 222 extracted.
Results from Page 223 extracted.
Results from Page 224 extracted.
Results from Page 225 extracted.
Results from Page 226 extracted.
Results from Page 227 extracted.
Results from Page 228 extracted.
Results from Page 229 extracted.
Results from Page 230 extracted.
Results from Page 231 extracted.
Results from Page 232 extracted.
Results from Page 233 extracted.
Results from Page 234 extracted.
Results from Page 235 extracted.
Results from Page 236 extracted.
Results from Page 237 extracted.
Results from Page 238 extracted.
Results from Page 239 extracted.
Results from Page 240 extracted.
Results from Page 241 extracted.
Results from Page 242 extracted.
Results from Page 243 extracted.
Results from Page 244 extracted.
Results from Page 245 extracted.
Results from Page 246 extracted.
Results from Page 247 extracted.
Results from Page 248 extracted.
Results from Page 249 extracted.
Results from Page 250 extracted.
Results from Page 251 extracted.
Results from Page 252 extracted.
Results from Page 253 extracted.
Results from Page 254 extracted.
Results from Page 255 extracted.
Results from Page 256 extracted.
Results from Page 257 extracted.
Results from Page 258 extracted.
Results from Page 259 extracted.
Results from Page 260 extracted.
Results from Page 261 extracted.
Results from Page 262 extracted.
Results from Page 263 extracted.
Results from Page 264 extracted.
Results from Page 265 extracted.
Results from Page 266 extracted.
Results from Page 267 extracted.
Results from Page 268 extracted.
Results from Page 269 extracted.
Results from Page 270 extracted.
Results from Page 271 extracted.
Results from Page 272 extracted.
Results from Page 273 extracted.
Results from Page 274 extracted.
Results from Page 275 extracted.
Results from Page 276 extracted.
Results from Page 277 extracted.
Results from Page 278 extracted.
Results from Page 279 extracted.
Results from Page 280 extracted.
Results from Page 281 extracted.
Results from Page 282 extracted.
Results from Page 283 extracted.
Results from Page 284 extracted.
Results from Page 285 extracted.
Results from Page 286 extracted.
Results from Page 287 extracted.
Results from Page 288 extracted.
Results from Page 289 extracted.
Results from Page 290 extracted.
Results from Page 291 extracted.
Results from Page 292 extracted.
Results from Page 293 extracted.
Results from Page 294 extracted.
Results from Page 295 extracted.
Results from Page 296 extracted.
Results from Page 297 extracted.
Results from Page 298 extracted.
Results from Page 299 extracted.
Results from Page 300 extracted.
Results from Page 301 extracted.
Results from Page 302 extracted.
Results from Page 303 extracted.
Results from Page 304 extracted.
Results from Page 305 extracted.
Results from Page 306 extracted.
Results from Page 307 extracted.
Results from Page 308 extracted.
Results from Page 309 extracted.
Results from Page 310 extracted.
Results from Page 311 extracted.
Results from Page 312 extracted.
Results from Page 313 extracted.
Results from Page 314 extracted.
Results from Page 315 extracted.
Results from Page 316 extracted.
Results from Page 317 extracted.
Results from Page 318 extracted.
Results from Page 319 extracted.
Results from Page 320 extracted.
Results from Page 321 extracted.
Results from Page 322 extracted.
Results from Page 323 extracted.
Results from Page 324 extracted.
Results from Page 325 extracted.
Results from Page 326 extracted.
Results from Page 327 extracted.
Results from Page 328 extracted.
Results from Page 329 extracted.
Results from Page 330 extracted.
Results from Page 331 extracted.
Results from Page 332 extracted.
Results from Page 333 extracted.
Results from Page 334 extracted.
Results from Page 335 extracted.
Results from Page 336 extracted.
Results from Page 337 extracted.
Results from Page 338 extracted.
Results from Page 339 extracted.
Results from Page 340 extracted.
Results from Page 341 extracted.
Results from Page 342 extracted.
Results from Page 343 extracted.
Results from Page 344 extracted.
Results from Page 345 extracted.
Results from Page 346 extracted.
Results from Page 347 extracted.
Results from Page 348 extracted.
Results from Page 349 extracted.
Results from Page 350 extracted.
Results from Page 351 extracted.
Results from Page 352 extracted.
Results from Page 353 extracted.
Results from Page 354 extracted.
Results from Page 355 extracted.
Results from Page 356 extracted.
Results from Page 357 extracted.
Results from Page 358 extracted.
Results from Page 359 extracted.
Results from Page 360 extracted.
Results from Page 361 extracted.
Results from Page 362 extracted.
Results from Page 363 extracted.
Results from Page 364 extracted.
Results from Page 365 extracted.
Results from Page 366 extracted.
Results from Page 367 extracted.
Results from Page 368 extracted.
Results from Page 369 extracted.
Results from Page 370 extracted.
Results from Page 371 extracted.
Results from Page 372 extracted.
Results from Page 373 extracted.
Results from Page 374 extracted.
Results from Page 375 extracted.
Results from Page 376 extracted.
Results from Page 377 extracted.
Results from Page 378 extracted.
Results from Page 379 extracted.
Results from Page 380 extracted.
Results from Page 381 extracted.
Results from Page 382 extracted.
Results from Page 383 extracted.
Results from Page 384 extracted.
Results from Page 385 extracted.
Results from Page 386 extracted.
Results from Page 387 extracted.
Results from Page 388 extracted.
Results from Page 389 extracted.
Results from Page 390 extracted.
Results from Page 391 extracted.
Results from Page 392 extracted.
Results from Page 393 extracted.
Results from Page 394 extracted.
Results from Page 395 extracted.
Results from Page 396 extracted.
Results from Page 397 extracted.
Results from Page 398 extracted.
Results from Page 399 extracted.
Results from Page 400 extracted.
Results from Page 401 extracted.
Results from Page 402 extracted.
Results from Page 403 extracted.
Results from Page 404 extracted.
Results from Page 405 extracted.
Results from Page 406 extracted.
Results from Page 407 extracted.
Results from Page 408 extracted.
Results from Page 409 extracted.
Results from Page 410 extracted.
Results from Page 411 extracted.
Results from Page 412 extracted.
Results from Page 413 extracted.
Results from Page 414 extracted.
Results from Page 415 extracted.
Results from Page 416 extracted.
Results from Page 417 extracted.
Results from Page 418 extracted.
Results from Page 419 extracted.
Results from Page 420 extracted.
Results from Page 421 extracted.
Results from Page 422 extracted.
Results from Page 423 extracted.
Results from Page 424 extracted.
Results from Page 425 extracted.
Results from Page 426 extracted.
Results from Page 427 extracted.
Results from Page 428 extracted.
Results from Page 429 extracted.
Results from Page 430 extracted.
Results from Page 431 extracted.
Results from Page 432 extracted.
Results from Page 433 extracted.
Results from Page 434 extracted.
Results from Page 435 extracted.
Results from Page 436 extracted.
Results from Page 437 extracted.
Results from Page 438 extracted.
Results from Page 439 extracted.
Results from Page 440 extracted.
Results from Page 441 extracted.
Results from Page 442 extracted.
Results from Page 443 extracted.
Results from Page 444 extracted.
Results from Page 445 extracted.
Results from Page 446 extracted.
Results from Page 447 extracted.
Results from Page 448 extracted.
Results from Page 449 extracted.
Results from Page 450 extracted.
Results from Page 451 extracted.
Results from Page 452 extracted.
Results from Page 453 extracted.
Results from Page 454 extracted.
Results from Page 455 extracted.
Results from Page 456 extracted.
Results from Page 457 extracted.
Results from Page 458 extracted.
Results from Page 459 extracted.
Results from Page 460 extracted.
Results from Page 461 extracted.
Results from Page 462 extracted.
Results from Page 463 extracted.
Results from Page 464 extracted.
Results from Page 465 extracted.
Results from Page 466 extracted.
Results from Page 467 extracted.
Results from Page 468 extracted.
Results from Page 469 extracted.
Results from Page 470 extracted.
Results from Page 471 extracted.
Results from Page 472 extracted.
Results from Page 473 extracted.
Results from Page 474 extracted.
Results from Page 475 extracted.
Results from Page 476 extracted.
Results from Page 477 extracted.
Results from Page 478 extracted.
Results from Page 479 extracted.
Results from Page 480 extracted.
Results from Page 481 extracted.
Results from Page 482 extracted.
Results from Page 483 extracted.
Results from Page 484 extracted.
Results from Page 485 extracted.
Results from Page 486 extracted.
Results from Page 487 extracted.
Results from Page 488 extracted.
Results from Page 489 extracted.
Results from Page 490 extracted.
Results from Page 491 extracted.
Results from Page 492 extracted.
Results from Page 493 extracted.
Results from Page 494 extracted.
Results from Page 495 extracted.
Results from Page 496 extracted.
Results from Page 497 extracted.
Results from Page 498 extracted.
Results from Page 499 extracted.

In [105]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,86.3449,8.911,1899
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,163.2599,8.724,30727
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,170.1650,8.703,3383
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,39.4047,8.687,23134
4,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,167.2060,8.675,5868
...,...,...,...,...,...,...,...
9975,73936,Retreat,Kate and Martin escape from personal tragedy t...,2011-10-14,0.7010,5.591,337
9976,9776,Head of State,When a presidential candidate dies unexpectedl...,2003-03-28,1.5889,5.591,320
9977,68684,Detention,As a killer named Cinderhella stalks the stude...,2012-04-06,1.2281,5.590,418
9978,10075,Blood and Chocolate,A young teenage werewolf is torn between honor...,2007-01-26,1.4292,5.590,334
9979,718444,Rogue,Battle-hardened O’Hara leads a lively mercenar...,2020-08-20,1.5677,5.589,746

In [106]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=7fbc7861cb903f427b0dfbe8f72a6be3&language=en-US&page=501')

In [107]:
response.json()

{'success': False,
 'status_code': 22,
 'status_message': 'Invalid page: Pages start at 1 and max at 500. They are expected to be an integer.'}

In [108]:
df.shape

(9980, 7)

In [109]:
df.to_csv('movies.csv')